version: '3'
services:
  stock_portfolio:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: 'stock_portfolio'
    working_dir: '/root/'
    tty: true
    volumes:
      - ./src:/root/src
      - ./config:/root/config
