version: '3'
services:
  python3:
    restart: always
    build: .
    container_name: 'stock_portfolio'
    working_dir: '/root/'
    tty: true
    volumes:
      - ./src:/root/src
      - ./config:/root/config
